### ISSUE TITLE
api.GPUDevice.importExternalTexture - Incorrect Firefox support version

### ISSUE THREAD

**Issue by Chainsawkitten** [mdn/browser-compat-data#27715]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

`GPUDevice.importExternalTexture` is listed as supported from Firefox 141 (Windows only). Firefox 141 did add WebGPU support, but this particular function was not supported.

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

`GPUDevice.importExternalTexture` is not yet supported in any stable Firefox release but is available in Nightly 144.0a1.

### Did you test this? If so, how?

The [video uploading WebGPU sample](https://webgpu.github.io/webgpu-samples/sample/videoUploading/) fails on Firefox 142.0.1 on Windows with:
`Uncaught TypeError: device.importExternalTexture is not a function`
(as well as shader compilation error due to `texture_external` in the shader).

It works in Firefox Nightly (144.0a1) on Windows.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

[GPUDevice.importExternalTexture MDN page](https://developer.mozilla.org/en-US/docs/Web/API/GPUDevice/importExternalTexture)
[144.0a1 release notes](https://www.firefox.com/en-US/firefox/144.0a1/releasenotes/)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/GPUDevice/importExternalTexture

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.GPUDevice.importExternalTexture`
* Report started: 2025-08-31T17:33:44.383Z

</details>

**Comment by caugner** [comment]
Thanks for reporting, meanwhile fixed via https://github.com/mdn/browser-compat-data/commit/b003833a63904fbe2bd0dfa45faecaef80f873e2#diff-a8e69063d00b2b27f64643edd133dbcbfc3728176ca687e6a94bb6c6c4b4af29R1785.
